AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Hello World API

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      CodeUri: .
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloApi:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
